import time

import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input,Output
import plotly.graph_objs as go


# Periodically reads the log file from the beginning to the end
# The log file is generated by the RandomNumberGenerator.py
# Outputs a graph of random numbers in an integer interval


f = open("testing_communication.log", "r")

def ReadData():

    data = {
        'interval':[],
        'data':[]
    }

    for line in f:
        lineSplit = line.split(",")
        data['interval'].append(int(lineSplit[0]))
        data['data'].append(int(lineSplit[1]))
    f.seek(0)
    return data


external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

startTime = time.process_time()
interval = [startTime]

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
app.layout = html.Div([

    html.H4('Testing Live Update'),
    dcc.Graph(id='live_update_graph'),
    dcc.Interval(
        id='interval',
        interval=1*1000,
        n_intervals=0
    )
])

@app.callback(Output('live_update_graph', 'figure'),
              [Input('interval', 'n_intervals')])
def update_graph_live(n):

    dataLog = ReadData()

    trace = go.Scatter(
        x = dataLog['interval'],
        y = dataLog['data'],
        mode = 'lines'
    )

    data = [trace]
    figure = go.Figure(data=data)

    return figure


if __name__ == '__main__':
    app.run_server(debug=True)
